### PR TITLE
Remove the cas-status cookie to fix 403 errors

### PR DESCRIPTION
**Pull request by sfuhrm**
The `cas-status` cookie is not working as intended and breaks setups with a server responding to _multiple_ DNS names where the

- first requests server sets the cas-status (`HOSTNAME_A`)
- and the second request server will get another cookie (cas service host, `HOSTNAME_B`).

Cookies set for `HOSTNAME_A` will not be sent to `HOSTNAME_B` and vice versa.

**Problem description:** We got sporadic `403` errors on our side every 2 accesses to `HOSTNAME_A`. This was still while requesting data from `HOSTNAME_A`.

**Problem cause:** The cookie for `HOSTNAME_A` was counted to the maximum and then a 403 error will be returned. The cookie for `HOSTNAME_A` was never reset because this was done on the side of `HOSTNAME_B`.

**Problem solution:** Removing the cookie from the code solved the problem.

It is not clear what the cookie was intended for, as it is stored in the client and the client can manipulate all cookies.

If I've missed an important use-case of the cookie, please let me know.

### CODE REVIEW

**Comment by ceharris** [comment]
The purpose of the cookie is really to prevent endless redirects when the user can't be authenticated for whatever reason. It's basically just a retry counter, as you observed. It really doesn't matter that the client can manipulate the cookie, since it's not a security feature.

It's probably fine to provide a configuration option to disable the use of the cookie, or perhaps simply allow the maximum retry count to be set much higher, either of which would solve your issue.

**Comment by sfuhrm** [comment]
@ceharris  I'm working on a new branch for this and could need some help.

Here:

https://github.com/1and1/cas-extension/blob/1e4d8e3c45c5381e57345644a088d6f830240eee/cas-subsystem/src/main/java/org/soulwing/cas/undertow/CasAuthenticationMechanism.java#L72

the `InjectedValue` does not get set by the container. 
Maybe you have a quick hint for me?

**Comment by ceharris** [comment]
The JBoss MSC doesn't do any automatic dependency injection. When you register a service, you have to know its dependencies and introduce them to the service by passing injector references.

But, before we get there, you first need to note that `CasAuthenticationMechanism` is a POJO, not a service, so it gets all of its dependencies via its constructor.

In `CasServletExtension.handleDeployment` you'll see where we're constructing an instance of the auth mechanism. It would be tempting to try to inject an instance of `Profile` directly into the servlet extension and pass it to the constructor, but that's probably going to be a rather complicated approach, because of the way the profile is selected for a deployment during deployment processing.

Instead, we could add a method to the `AuthenticationService` interface to return the associated `Configuration` object. We want to use `Configuration` instead of the `Profile` subtype to avoid creating a circular dependency between the `service` package and the `extension` and `deployment` packages.

```
public interface AuthenticationService {
  Configuration getConfiguration();
}
```

This can be implemented in `CasAuthenticationService` by straight delegation, just like the other methods in that type. In `DeploymentAuthenticationService` (which already gets injected with the correct `Profile`) you can implement it as:

```
public Configuration getConfiguration() {
  return profile.getValue();
}
```

Then, back in the `CasAuthenticationMechanism` you can use `authenticationService.getConfiguration().isCasStatusCookieEnabled()` to determine whether the cookie type is real or no-op.

**Comment by ceharris** [comment]
A few other things you'll probably need to address, if you haven't already noticed them:

1.  Update the message bundle in src/main/resources to specify descriptive text used by the Wildfly CLI, so that it includes your new configuration attribute.
2. Update the XML schema (src/main/resources/cas.xsd) to include your new attribute.
3. Modify `ProfileService.createProfile` to copy the value specified in the profile management model into the `Profile` instance that will be held by the service.

**Comment by sfuhrm** [comment]
@ceharris  thanks for your kind help!
Will close this PR and issue a new one as soon as I have tested the code.

**Pull request closed without merging**
